### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by NotJustAnna** [adriantodt/DragonScalesEXMod#9]
- [ ] Add Virus barrier, creating a barrier for Dracony Virus size 5x255x5 (Bedrock through Sky), where the Virus won't propagate no matter what.
- [ ] Add a Flower that do the same but in 3x255x3 , just because stetic.
- [ ] Fix Sapling
- [ ] Add Dracony Botania
- [ ] Add a Dracony equivalent of Sand, Gravel and Clay at the same time, and register in the virus
- [ ] Add a Proper VirusRegistry
- [ ] Add an Overpowered Virus Barrier, that reverts changes in 7x255x7, as well as blocking spawn in a 9x255x9 range.
- [ ] Make Virus much more rare, and much more slower (Both Toggleable)
- [ ] Transform the Virus into a Biome
- [ ] Add Dragons to the Biome
- [ ] Make the Virus Block "Hold" an NBT with the previous Block (For proper Undo)
- [ ] Add a Sky-Dimension like of the Biome
- [ ] Add a Ritual
- [ ] DynamicCraft integration
- [ ] Create Dracony-Type Ores, and Register as a Vanilla/Mod Ore would be eaten by the virus (Like Iron, Gold, Copper, Tin etc turning into DragonMetal, etc)
- [ ] Add more uses to DragonMetal
- [x] Create a proper good Crafting Manager (Internal)
- [ ] Finish the Hopper-like block and remove the other block.
- [ ] Texture Revamp (again)
- [x] Start "Project DragonTech" in the mod.

**Comment by NotJustAnna** [comment]
Update:
1, 2, 7, 8: VirusStates and GridSystem implemented. Virus Related Things will be moved to /virus/, and will have a Separate Event Handler.

**Comment by NotJustAnna** [comment]
Update:
5: the Registry is mostly done. needs an Instance somewhere ._.
17: okay.
18: the other block have been removed.
19: yep.
